# Generated by Django 4.2.29 on 2026-03-31 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight (kg)', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weight Readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SugarLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_level', models.DecimalField(decimal_places=1, help_text='Blood glucose level (mg/dL)', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('meal_timing', models.CharField(choices=[('fasting', 'Fasting'), ('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('bedtime', 'Bedtime')], default='fasting', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_level_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sugar Level Readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(help_text='Systolic pressure (mmHg)')),
                ('diastolic', models.IntegerField(help_text='Diastolic pressure (mmHg)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blood Pressure Readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
